jQuery(window).load(function() { "use strict";
    document.body.clientWidth >= besclwp_sticky_vars.besclwp_sticky_breakpoint && "none" !== besclwp_sticky_vars.besclwp_sticky_behavior && jQuery("#besocial-content-inner").find(".besclwp-page-right").theiaStickySidebar({ additionalMarginTop: besclwp_sticky_vars.besclwp_sticky_top, additionalMarginBottom: besclwp_sticky_vars.besclwp_sticky_bottom, sidebarBehavior: besclwp_sticky_vars.besclwp_sticky_behavior }), jQuery("#besocial-content-inner").find(".besclwp-faq-left").theiaStickySidebar({ additionalMarginTop: besclwp_sticky_vars.besclwp_sticky_top, additionalMarginBottom: besclwp_sticky_vars.besclwp_sticky_bottom, sidebarBehavior: besclwp_sticky_vars.besclwp_sticky_behavior }), jQuery("#buddypress").find("#item-nav").theiaStickySidebar({ additionalMarginTop: besclwp_sticky_vars.besclwp_sticky_top, additionalMarginBottom: besclwp_sticky_vars.besclwp_sticky_bottom, sidebarBehavior: besclwp_sticky_vars.besclwp_sticky_behavior }) }), jQuery(window).on("resize orientationchange", function() { "use strict";
    document.body.clientWidth >= besclwp_sticky_vars.besclwp_sticky_breakpoint ? (jQuery(".theiaStickySidebar").contents().unwrap(), setTimeout(function() { "none" !== besclwp_sticky_vars.besclwp_sticky_behavior && jQuery("#besocial-content-inner").find(".besclwp-page-right").theiaStickySidebar({ additionalMarginTop: besclwp_sticky_vars.besclwp_sticky_top, additionalMarginBottom: besclwp_sticky_vars.besclwp_sticky_bottom, sidebarBehavior: besclwp_sticky_vars.besclwp_sticky_behavior }), jQuery("#besocial-content-inner").find(".besclwp-faq-left").theiaStickySidebar({ additionalMarginTop: besclwp_sticky_vars.besclwp_sticky_top, additionalMarginBottom: besclwp_sticky_vars.besclwp_sticky_bottom, sidebarBehavior: besclwp_sticky_vars.besclwp_sticky_behavior }), jQuery("#buddypress").find("#item-nav").theiaStickySidebar({ additionalMarginTop: besclwp_sticky_vars.besclwp_sticky_top, additionalMarginBottom: besclwp_sticky_vars.besclwp_sticky_bottom, sidebarBehavior: besclwp_sticky_vars.besclwp_sticky_behavior }) }, 100)) : jQuery(".theiaStickySidebar").contents().unwrap() 


});



